
{
    "startHour":"9",
    "endHour":"20",
    "grad_tas":[
        {
            "name":"asdfq",
            "email":"sadfwef@130.casd",
            "type":"Graduate"
        }
    ],
    "undergrad_tas":[
        {
            "name":"asdfw",
            "email":"sdfe899@asd.css",
            "type":"Undergraduate"
        }
    ],
    "officeHours":[
        {
            "time":"9_00am",
            "day":"MONDAY",
            "name":"asdfw"
        },
        {
            "time":"9_00am",
            "day":"WEDNESDAY",
            "name":"asdfq"
        },
        {
            "time":"9_30am",
            "day":"MONDAY",
            "name":"asdfq"
        },
        {
            "time":"9_30am",
            "day":"TUESDAY",
            "name":"asdfw"
        },
        {
            "time":"9_30am",
            "day":"WEDNESDAY",
            "name":"asdfq"
        },
        {
            "time":"9_30am",
            "day":"WEDNESDAY",
            "name":"asdfw"
        },
        {
            "time":"9_30am",
            "day":"THURSDAY",
            "name":"asdfq"
        },
        {
            "time":"10_00am",
            "day":"MONDAY",
            "name":"asdfw"
        },
        {
            "time":"10_00am",
            "day":"TUESDAY",
            "name":"asdfw"
        },
        {
            "time":"10_00am",
            "day":"WEDNESDAY",
            "name":"asdfq"
        },
        {
            "time":"10_30am",
            "day":"MONDAY",
            "name":"asdfq"
        },
        {
            "time":"10_30am",
            "day":"MONDAY",
            "name":"asdfw"
        },
        {
            "time":"10_30am",
            "day":"TUESDAY",
            "name":"asdfq"
        },
        {
            "time":"10_30am",
            "day":"WEDNESDAY",
            "name":"asdfw"
        }
    ],
    "site":[
        {
            "subject":"CSE",
            "number":"220",
            "semester":"Spring",
            "year":"2018",
            "title":"CS III",
            "css":"sea_wolf.css",
            "instructor_name":"holin",
            "instructor_room":"rew",
            "instructor_email":"asd@out.cm",
            "instructor_homepage":"test",
            "instructor_oh":"[\n            {\n                \"day\":\"Tuesday\",\n                \"time\":\"1:00pm-2:20pm\"\n            },\n            {\n                \"day\":\"Wednesday\",\n                \"time\":\"2pm-3pm\"\n            },\n            {\n                \"day\":\"Thursday\",\n                \"time\":\"1:00pm-2:20pm\"\n            }\n        ]",
            "favicon":"file:C:/Users/Jxsry/Documents/NetBeansProjects/CSE219/hw4/CourseSiteGenerator/apps/CourseSite/original_web/images/Favicon.ico",
            "navbar":"file:C:/Users/Jxsry/Documents/NetBeansProjects/CSE219/hw4/CourseSiteGenerator/apps/CourseSite/original_web/images/SBUDarkRedShieldLogo.png",
            "bottom_left":"file:./images/Style/SBU/SBUWhiteShieldLogo.jpg",
            "bottom_right":"file:./images/Style/SBU/SBUCSLogo.png"
        }
    ],
    "syllabus":[
        {
            "description":"Development of the basic concepts and techniques from Computer Science I and II into practical programming skills that include a systematic approach to program design, coding, testing, and debugging. Application of these skills to the construction of robust programs of thousands of lines of source code. Use of programming environments and tools to aid in the software development process.",
            "topics":"[\n        \"Programming style and its impact on readability, reliability, maintainability, and portability.\",\n        \"Decomposing problems into modular designs with simple, narrow interfaces.\",\n        \"Determining the proper objects in an object-oriented design.\",\n        \"Selecting appropriate algorithms and data structures.\",\n        \"Reusing code, including external libraries designed and built by others.\",\n        \"Learning systematic testing and debugging techniques.\",\n        \"Maintaining a repository of code during incremental development of a software project.\",\n        \"Learning how to use threads to synchronize several tasks.\",\n        \"Improving program performance.\",\n        \"Making effective use of a programming environment, including:<br /><ul><li>Syntax-directed editor</li><li>Build tools</li><li>Debugging tools</li><li>Testing tools</li><li>Source code management tools</li><li>Profiling tools</li></ul>\"\n    ]",
            "prerequisites":"You must have taken CSE 214 and received a grade of 'C' or better in order to take this course. In more detail, you are expected to have the following knowledge and skills at the beginning of the course:<br /><ul><li>Ability to write programs of a few hundred lines of code in the Java programming language.</li><li>Understanding of fundamental data structures, including lists, binary trees, hash tables, and graphs, and the ability to employ these data structures in the form provided by the standard Java API.</li><li>Ability to construct simple command-based user interfaces, and to use files for the input and output of data.</li><li>Mastery of basic mathematical and geometric reasoning using pre-calculus concepts.</li></ul>",
            "outcomes":" [\n        \"Ability to systematically design, code, debug, and test programs of about two thousand lines of code.\",\n        \"Sensitivity to the issues of programming style and modularity and their relationship to the construction and evolution of robust software.\",\n        \"Knowledge of basic ideas and techniques of object-oriented programming.\",\n        \"Familiarity with the capabilities and use of programming tools such as syntax-directed editors, debuggers, execution profilers, documentation generators, and revison-control systems.\"\n    ]",
            "textbooks":"[\n        {\n            \"title\": \"Head First Object Oriented Analysis and Design\",\n            \"link\": \"http://proquestcombo.safaribooksonline.com.proxy.library.stonybrook.edu/0596008678\",\n            \"photo\": \"./images/HeadFirstOOAAD.jpg\",\n            \"authors\": [\n                \"Brett McLaughlin\", \"Gary Pollice\", \"David West\"\n            ],\n            \"publisher\": \"O'Reilly Media, Inc.\",\n            \"year\": \"2006\"\n        },\n        {\n            \"title\": \"Head First Design Patterns\",\n            \"link\": \"http://proquestcombo.safaribooksonline.com.proxy.library.stonybrook.edu/0596007124\",\n            \"photo\": \"./images/HeadFirstDesignPatterns.gif\",\n            \"authors\": [\n                \"Eric T Freeman\", \"Elisabeth Robson\", \"Bert Bates\", \"Kathy Sierra\"\n            ],\n            \"publisher\": \"O'Reilly Media, Inc.\",\n            \"year\": \"2004\"\n        }\n    ]",
            "graded":"[\n        {\n            \"name\": \"Recitations\",\n            \"description\": \"Students will attend weekly recitations that will introduce use of essential development tools and will require completion of an exercise for submission.\",\n            \"weight\": \"10\"\n        },\n        {\n            \"name\": \"Homework Assignments\",\n            \"description\": \"The assignments will develop a students ability to design and implement object-oriented systems. Grading will be based on functionality and proper use specific tools. Submitted code that does not compile will receive no credit. Late submissions will NOT be accepted. Programming assignments will be handed in electronically, instructions for which will be provided early in the semester.\",\n            \"weight\": \"20\"\n        },\n        {\n            \"name\": \"Final Project\",\n            \"description\": \"The assignments will build to the final project, which will be a fully functioning application.\",\n            \"weight\": \"20\"\n        },\n        {\n            \"name\": \"Midterm Exam\",\n            \"description\": \"The midterm will cover all lecture, quizzes, and homework materials covered during the first 1/2 of the semester.\",\n            \"weight\": \"20\"\n        },\n        {\n            \"name\": \"Final Exam\",\n            \"description\": \"The final will be cumulative and will cover all lecture, reading, and homework material.\",\n            \"weight\": \"30\"\n        }\n    ]",
            "grading_note":"<strong>Note CEAS Policy:</strong> The Pass/No Credit (P/NC) option is not available for this course.",
            "academic_dishonesty":"You may <em>discuss</em> the homework in this course with anyone you like, however each student's submissionmust be ones own work.<br /><br />The College of Engineering and Applied Sciences regards academic dishonesty as a very serious matter, and provides for substantial penalties in such cases. For more information, obtain a copy of the CEAS guidelines on academic dishonesty from the CEAS office.<br /><br /><strong>Be advised that any evidence of academic dishonesty will be treated with utmost seriousness. If you have a situation that may tempt you into doing something academically dishonest, resist the urge and speak with your instructor during office hours for help.</strong><br /><br />",
            "special_assistance":"If you have a physical, psychological, medical or learning disability that may impact on your ability to carry out assigned course work, I would urge that you contact the staff at the <a href='https://www.stonybrook.edu/dss/'>Student Accessibility Support Center</a> (SASC) in the ECC building, 632-6748. SASC will review your concerns and determine with you what accommodations are necessary and appropriate. All information and documentation of disability are confidential.<br /><br /><br /><br />"
        }
    ],
    "lectures":[
        {
            "section":"a",
            "days":"b",
            "time":"e",
            "room":"f"
        },
        {
            "section":"e",
            "days":"e",
            "time":"c",
            "room":"z"
        }
    ],
    "recitations":[
        {
            "section":"eets",
            "exact":"ase",
            "room":"asdfe",
            "ta1":"ewaw",
            "ta2":"cavs"
        }
    ],
    "labs":[
        {
            "section":"asdfe",
            "exact":"sadfew",
            "room":"asdfe",
            "ta1":"ewqf",
            "ta2":"asdfe"
        }
    ],
    "calendar":[
        {
            "calendar_start":"12/10/2018",
            "calendar_end":"12/21/2018"
        }
    ],
    "schedule_items":[
        {
            "type":"Holiday",
            "date":"12/12/2018",
            "title":"tsets",
            "topic":"",
            "link":"serw"
        },
        {
            "type":"HW",
            "date":"12/12/2018",
            "title":"test",
            "topic":"Newtest",
            "link":"nono"
        },
        {
            "type":"Lecture",
            "date":"12/10/2018",
            "title":"tesat",
            "topic":"asdf",
            "link":"wqefqw"
        },
        {
            "type":"Recitation",
            "date":"12/20/2018",
            "title":"test",
            "topic":"sadf",
            "link":"ewqfwer"
        },
        {
            "type":"Reference",
            "date":"12/11/2018",
            "title":"asdfe",
            "topic":"qwef",
            "link":"qwefqe"
        },
        {
            "type":"Reference",
            "date":"12/13/2018",
            "title":"asdfe",
            "topic":"eqfwe",
            "link":"wqefqw"
        },
        {
            "type":"HW",
            "date":"12/12/2018",
            "title":"sdfwe",
            "topic":"wqefq",
            "link":"qwef"
        }
    ]
}